---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # CustomResourceDefinitions
  - ./customresourcedefinitions/scheduledworkflows.yaml

  # Deployments
  - ./deployments/ds-pipeline-persistenceagent.yaml
  - ./deployments/ds-pipeline-scheduledworkflow.yaml
  - ./deployments/ds-pipeline.yaml

  # Rolebindings
  - ./rolebindings/ds-pipeline-scheduledworkflow-binding.yaml
  - ./rolebindings/ds-pipeline.yaml
  - ./rolebindings/pipeline-runner-binding.yaml

  # Roles
  - ./roles/ds-pipeline-scheduledworkflow-role.yaml
  - ./roles/ds-pipeline.yaml
  - ./roles/pipeline-runner.yaml

  # ClusterRoleBindings
  - ./clusterrolebindings/ds-pipeline-persistenceagent-clusterrolebinding.yaml

  # ClusterRoles
  - ./clusterroles/ds-pipeline-persistenceagent-clusterrole.yaml

  # ServiceAccounts
  - ./serviceaccounts/ds-pipeline-container-builder.yaml
  - ./serviceaccounts/ds-pipeline-persistenceagent.yaml
  - ./serviceaccounts/ds-pipeline-scheduledworkflow.yaml
  - ./serviceaccounts/ds-pipeline.yaml
  - ./serviceaccounts/pipeline-runner.yaml

  # Services
  - ./services/ds-pipeline.yaml

  # Monitoring
  - ../prometheus

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ds-pipeline-params-config
    envs:
      - params.env
vars:
  - name: artifact_secret_name
    objref:
      name: ds-pipeline-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.artifact_secret_name
  - name: pipeline_install_configuration
    objref:
      name: ds-pipeline-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.pipeline_install_configuration
  - name: ds_pipelines_configuration
    objref:
      name: ds-pipeline-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.ds_pipelines_configuration
  - name: database_secret
    objref:
      name: ds-pipeline-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.database_secret
  - name: ds_pipelines_ui_configuration
    objref:
      name: ds-pipeline-params-config
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.ds_pipelines_ui_configuration

configurations:
  - params.yaml

images:
  - name: persistenceagent
    newName: quay.io/modh/odh-ml-pipelines-persistenceagent-container
    newTag: v1.18.0-8
  - name: scheduledworkflow
    newName: quay.io/modh/odh-ml-pipelines-scheduledworkflow-container
    newTag: v1.18.0-8
  - name: viewer-crd-controller
    newName: quay.io/modh/odh-ml-pipelines-viewercontroller-container
    newTag: v1.18.0-8
  - name: api-server
    newName: quay.io/modh/odh-ml-pipelines-api-server-container
    newTag: v1.18.0-8
